export const SELECT_FILE = 'SELECT_FILE';
export const MODIFY_CONTENT = 'MODIFY_CONTENT';
export const REMOVE_TAB = 'REMOVE_TAB';
export const MODIFY_BRANCH_MODAL_VISIBILITY = 'MODIFY_BRANCH_MODAL_VISIBILITY';
export const SELECT_BRANCH = 'SELECT_BRANCH';
export const SET_STORED_FILES = 'SET_STORED_FILES';
